#[tomlConfig]
version = "0.0.4"   # версия конфигурационного файла
# 0.0.1 - начальная версия
# 0.0.2 - несколько портов, насколько устройств (нод) на порту
# 0.0.3 - добавлены порты по TCP на порту
upport_tcp = 45502  # порт для системы верхего уровня
local_port = 17000
count_tty_serial = 0        # должно быть реальное значение каналов
count_tcp_serial = 1

[[tcp_serial]]
# с версии 0.17 указыавем полный путь к устройству
    mode = "TCP"        # or UDP - пока UDP не рассматриваем
#    ip = "10.0.0.9"
#   ip = "127.0.0.1"     # при отладке на симуляторе - localhost
   ip = "172.16.205.141"    # при отладке на симуляторе Modbus Slave через внешний IP
    port = 502          # port used
    time_loop = 500
    count_node = 5      # количество устройств на порту
# описание nede? как и в tty_serial
# input registers – ИЭ05-1
    [[tcp_serial.set_node]]
        enable = true          # работает или нет
        address_id = 1         # адрес устройства на шине (1..247)
        command = 3            # команда запроса – запрос INPUT регитстров из устройства
        address_data = 3       # адрес данных в устройстве
        data_length = 8        # длинна запрашиваемых данных только 30004-7
        index_up = 6          # индекс на общей карте параметров
        type_par = 1          # Тип параметра получаемого от такт-у 1-AI, 2-DI
# input registers – ИЭ05-2
    [[tcp_serial.set_node]]
        enable = true           # работает или нет
        address_id = 1          # адрес устройства на шине (1..247)
        command = 3             # команда запроса – запрос INPUT регитстров из устройства
        address_data = 13        # адрес данных в устройстве
        data_length = 4         # длинна запрашиваемых данных только
        index_up = 14          # индекс на общей карте параметров
        type_par = 1          # Тип параметра получаемого от такт-у 1-AI, 2-DI

# input registers – ДЭ07-1
    [[tcp_serial.set_node]]
        enable = true           # работает или нет
        address_id = 1          # адрес устройства на шине (1..247)
        command = 3             # команда запроса – запрос INPUT регитстров из устройства
        address_data = 22       # адрес данных в устройстве
        data_length = 1         # длинна запрашиваемых данных для дискрета 16 бит
        index_up = 1           # индекс на общей карте параметров
        type_par = 2            # Тип параметра получаемого от такт-у 1-AI, 2-DI

# кран – DO01 - КР01 - открыть
    [[tcp_serial.set_node]]
        enable = true           # работает или нет
        address_id = 0          # В двнном случае номер канала в модуле управления
        command = 5             # команда запроса – запрос INPUT регитстров из устройства
        address_data = 32768    # адрес данных в устройстве
        data_length = 1         # Количество команд открыть/закрыть 2 шт.
        index_up = 101           # индекс на общей карте параметров
        type_par = 3            # Тип параметра получаемого от такт-у 1-AI, 2-DI
# кран – DO01 - КР01 - закрыть
    [[tcp_serial.set_node]]
        enable = true           # работает или нет
        address_id = 8          # В двнном случае номер канала в модуле управления
        command = 5             # команда запроса – запрос INPUT регитстров из устройства
        address_data = 32768    # адрес данных в устройстве
        data_length = 1         # Количество команд открыть/закрыть 2 шт.
        index_up = 102           # индекс на общей карте параметров
        type_par = 3            # Тип параметра получаемого от такт-у 1-AI, 2-DI

# input registers – ДЭ07-2
    [[tcp_serial.set_node]]
        enable = true           # работает или нет
        address_id = 1          # адрес устройства на шине (1..247)
        command = 3             # команда запроса – запрос INPUT регитстров из устройства
        address_data = 24       # адрес данных в устройстве
        data_length = 1         # длинна запрашиваемых данных для дискрета 16 бит
        index_up = 16            # индекс на общей карте параметров
        type_par = 2            # Тип параметра получаемого от такт-у 1-AI, 2-DI

[[tcp_serial]]


