#[tomlConfig]
version = "0.0.4"
upport_tcp = 45502
local_port = 17000
count_tty_serial = 0
count_tcp_serial = 1
   
[[tcp_serial]]
   mode = "TCP"
   ip = "127.0.0.1"
#   ip = "172.16.205.141"
   port = 502
   time_loop = 400
   count_node = 5
   
   [[tcp_serial.set_node]]
       enable = true
       address_id = 1
       command = 3
       address_data = 22
       data_length = 1
       index_up = 10001
       type_par = 2
   
   [[tcp_serial.set_node]]
       enable = true
       address_id = 1
       command = 3
       address_data = 3
       data_length = 8
       index_up = 30001
       type_par = 1
   
       [[tcp_serial.set_node.Params]]
           id = 1
           Addres = 30001 
           Hi = "25.7"
           Low = "-100"

   
       [[tcp_serial.set_node.Params]]
           id = 2
           Addres = 30002 
           Hi = "10"
           Low = "0"

   
       [[tcp_serial.set_node.Params]]
           id = 3
           Addres = 30003 
           Hi = "10"
           Low = "0"

   
       [[tcp_serial.set_node.Params]]
           id = 4
           Addres = 30004 
           Hi = "10"
           Low = "0"

   
       [[tcp_serial.set_node.Params]]
           id = 5
           Addres = 30005 
           Hi = "10"
           Low = "0"

   
       [[tcp_serial.set_node.Params]]
           id = 6
           Addres = 30006 
           Hi = "10"
           Low = "0"

   
       [[tcp_serial.set_node.Params]]
           id = 7
           Addres = 30007 
           Hi = "60"
           Low = "0"

   
       [[tcp_serial.set_node.Params]]
           id = 8
           Addres = 30008 
           Hi = "100"
           Low = "-50"

   
   [[tcp_serial.set_node]]
       enable = true
       address_id = 1
       command = 3
       address_data = 13
       data_length = 7
       index_up = 30009
       type_par = 1

       [[tcp_serial.set_node.Params]]
           id = 9
           Addres = 30009
           Hi = "60"
           Low = "0"


       [[tcp_serial.set_node.Params]]
           id = 10
           Addres = 30010
           Hi = "60"
           Low = "0"


       [[tcp_serial.set_node.Params]]
           id = 11
           Addres = 30011
           Hi = "60"
           Low = "0"


       [[tcp_serial.set_node.Params]]
           id = 12
           Addres = 30012
           Hi = "50"
           Low = "-50"


       [[tcp_serial.set_node.Params]]
           id = 13
           Addres = 30013
           Hi = "60"
           Low = "0"


       [[tcp_serial.set_node.Params]]
           id = 14
           Addres = 30014
           Hi = "60"
           Low = "0"


       [[tcp_serial.set_node.Params]]
           id = 15
           Addres = 30015
           Hi = "50"
           Low = "-50"

   
   [[tcp_serial.set_node]]
       enable = true
       address_id = 1
       command = 3
       address_data = 24
       data_length = 1
       index_up = 10101
       type_par = 2
   
   [[tcp_serial.set_node]]
       enable = true
       address_id = 1
       command = 3
       address_data = 26
       data_length = 1
       index_up = 10201
       type_par = 2
   
   [[tcp_serial.set_node]]
       enable = true
       address_id = 1
       command = 3
       address_data = 28
       data_length = 1
       index_up = 10301
       type_par = 2
   
[[tcp_serial]]   
   
